### PR TITLE
fix improved fortifications so it can´t save against non-saveable effects anymore

### LINKED ISSUE #3019: Bug: Improved Fortifications can save against the sacrifice of The Kingsroad
As title says. You are not allowed to save against a sacrifice effect according to the rules, see https://thronesdb.com/rulesreference#Sacrifice

### PR DESCRIPTION
**Pull request by EvadLhorg**
resolves #3019

### CODE REVIEW

**Comment by ystros** [comment]
I think more is required to fix Improved Fortifications, though I'm surprised by the test failures here.

**Comment by EvadLhorg** [comment]
I added some stuff now but i am still very confused by the varys test or to be more specific the interaction between Arya Stark (TFM)´s no save effect and the interaction with dupes. The addition of {allowSave: allowSave} as a parameter to the moveCard call breaks the Varys test and it feels like the no-save vs dupe interaction only worked before because of a bug. Please help :D

**Comment by ystros** [comment]
I ran into similar issues when I tried fixing this issue. I think the *real* answer is to make the onCardLeftPlay event simultaneous to the other card move events. Which is a larger, harder change that does need to happen, but it's so large it's hard to get traction on.

**Comment by EvadLhorg** [comment]
not necessary anymore due to #3188 being merged

**Pull request closed without merging**
